name: Test Project
on: push # This will trigger this workflow when any branch pushed to remote
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # First step to download code to ubuntu server
      - name: Get code
        uses: actions/checkout@v4
    # Second step to install node version in ubuntu server
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
    # Third step is for installing libraries
      - name: Install dependencies
        run: npm ci # This command is used to install dependencies
    # Fourth step is for running tests
      - name: Run tests
        run: npm test